version: 2

sources:
  - name: walgreens
    schema: bioportal_sources
    freshness:
      error_after: { count: 1, period: day }
    loaded_at_field: >
      CAST(from_iso8601_timestamp(
      		regexp_extract("$path", '(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z'))
      		AS TIMESTAMP)
    tables:
      - name: walgreens_tracker_parquet_v1
        freshness: null
      - name: walgreens_tracker_parquet_v2
        freshness: null
      - name: walgreens_tracker_parquet_v3
        freshness: null
