version: 2

sources:
  - name: biostatistics
    meta:
      external_location: "{{ env_var('DATA_LAKE_ROOT')}}/biostatistics.salud.pr.gov/{name}/parquet_v2/*/*.parquet"
    freshness:
      error_after: { count: 1, period: day }
    loaded_at_field: downloadedAt
    tables:
      - name: cases
      - name: deaths
      - name: tests
