version: 2

sources:
  - name: hhs
    schema: covid_hhs_sources
    # I would love to use a macro here but apparently DBT hasn't read
    # them in yet when it interprets this field
    loaded_at_field: >
      CAST(parse_datetime(regexp_replace("$path",
                                          '^.*(202[0-9](\d{4})_(\d{4})).*$',
                                         '$1 America/New_York'),
                          'yyyyMMdd_HHmm ZZZ')
            AT TIME ZONE 'UTC'
            AS TIMESTAMP)
    tables:
      - name: reported_hospital_utilization_timeseries_v2
      - name: reported_hospital_utilization_timeseries_v3
        freshness:
          error_after: { count: 7, period: day }
      - name: reported_hospital_utilization_v2
      - name: reported_hospital_utilization_v3
        freshness:
          error_after: { count: 1, period: day }
      - name: hospital_facilities_v2
        identifier: reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries_v2
      - name: hospital_facilities_v3
        identifier: reported_hospital_capacity_admissions_facility_level_weekly_average_timeseries_v3
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 9, period: day }
      - name: community_profile_report_county_v2
      - name: community_profile_report_county_v3
        freshness:
          warn_after: { count: 5, period: day }
          error_after: { count: 7, period: day }
      - name: diagnostic_lab_testing_v2
      - name: diagnostic_lab_testing_v3
        freshness:
          warn_after: { count: 1, period: day }
          error_after: { count: 36, period: hour }
      - name: vaccination_county_condensed_data_json
        loaded_at_field: >
          CAST(from_iso8601_timestamp(
                regexp_extract("$path", '(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})Z'))
                AS TIMESTAMP)
        freshness:
          # I no longer pull this dataset, so it'll never be fresh again.
          warn_after: { count: 1, period: day }
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_v2
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_v3
        freshness:
          warn_after: { count: 31, period: day }
#          error_after: { count: 33, period: day }
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_and_booster_dose_v2
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_and_booster_dose_v3
        freshness:
          warn_after: { count: 31, period: day }
#          error_after: { count: 33, period: day }
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_and_second_booster_dose_v2
      - name: rates_of_covid_19_cases_or_deaths_by_age_group_and_vaccination_status_and_second_booster_dose_v3
        freshness:
          warn_after: { count: 31, period: day }
#          error_after: { count: 33, period: day }
      - name: community_levels_by_county_v2
      - name: community_levels_by_county_v3
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 9, period: day }
      - name: united_states_covid_19_cases_and_deaths_by_state_v3
      - name: weekly_united_states_covid_19_cases_and_deaths_by_state_v3
        freshness:
          error_after: { count: 7, period: day }
      - name: excess_deaths_associated_with_covid_19_v3
        freshness:
          warn_after: { count: 7, period: day }
          error_after: { count: 9, period: day }
