version: 2

models:
  - name: biostatistics_deaths_cube
    description: >
      Our most detailed aggregate table over `biostatistics_deaths`.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - bulletin_date
            - death_date
            - age_gte
            - region
            - vaccination_status_at_death

  - name: biostatistics_deaths_acs_age_agg
    description: >
      Deaths aggregated to American Community Survey age bands,
      with population estimates cooked in.
    tests:
      - dbt_utils.unique_combination_of_columns:
          combination_of_columns:
            - bulletin_date
            - death_date
            - acs_age_gte
