name: 'covid_19_puerto_rico_etl'
version: '2.0.0'
config-version: 2

profile: 'covid-19-puerto-rico-duckdb'

vars:
  earliest_downloaded_date: "{{ env_var('EARLIEST_DOWNLOADED_DATE', '2023-08-01')}}"
  latest_downloaded_date: "{{ env_var('LATEST_DOWNLOADED_DATE', '2100-12-31')}}"

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  covid_19_puerto_rico_etl:
    biostatistics:
      +materialized: 'external'

seeds:
  covid_19_puerto_rico_etl:
    census:
      acs_2019_5y_family_income:
        +column_types:
          fips: VARCHAR(5)
      acs_2019_5y_household_income:
        +column_types:
          fips: VARCHAR(5)
      acs_2019_5y_race:
        +column_types:
          fips: VARCHAR(5)
      municipal_population:
        +column_types:
          fips: VARCHAR(5)

    covid19datos_v2:
      covid19datos_v2_casos_city_names:
        +column_types:
          fips: VARCHAR(5)
      covid19datos_v2_vacunacion_city_names:
        +column_types:
          fips: VARCHAR(5)

    testing:
      expected_test_results:
        +column_types:
          # I'd like BOOLEAN here, but DBT won't load it
          positive: VARCHAR(5)

    other:
      municipal_abbreviations:
        +column_types:
          county: VARCHAR(3)
          fips: VARCHAR(5)
