covid-19-puerto-rico-duckdb:
  target: local
  outputs:

    local:
      type: duckdb
      extensions:
        - parquet
      threads: 4
      external_root: "{{ env_var('OUTPUT_ROOT') }}"

    aws:
      type: duckdb
      extensions:
        - httpfs
        - parquet
      threads: 4
      external_root: "{{ env_var('OUTPUT_ROOT') }}"
      use_credential_provider: aws

