covid-19-puerto-rico-duckdb:
  target: local
  outputs:

    local:
      type: duckdb
      extensions:
        - parquet
      threads: "{{ env_var('DBT_THREADS', 4) | as_number }}"
      external_root: "{{ env_var('OUTPUT_ROOT') }}"

    aws:
      type: duckdb
      extensions:
        - httpfs
        - parquet
      threads: "{{ env_var('DBT_THREADS', 4) | as_number }}"
      external_root: "{{ env_var('OUTPUT_ROOT') }}"
      use_credential_provider: aws
      settings:
        s3_region: "{{ env_var('S3_REGION') }}"

config:
  use_colors: False
