version: 2

models:
  - name: casos
    description: >
      The Puerto Rico Department of Health's daily COVID-19 cases datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per case.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: sample_date
        description: Test sample date.
        tests:
          - not_null:
              where: >
                downloaded_date < DATE '2023-05-12'
          - dbt_utils.accepted_range:
              min_value: DATE '2020-03-01'
              max_value: downloaded_at
              inclusive: true
      - name: class
        description: >
          What type of case this record represents, "confirmed" or "probable."
        tests:
          - not_null
          - accepted_values:
              values:
                - CONFIRMADO
                - PROBABLE
                - SOSPECHOSO
      - name: city
        description: >
          What municipality is recorded for the case.  Some official documentation
          suggests this is supposed to mean where the patient resides, but there
          has often been reason to suspect many cases might be recorded as the
          municipality of the test center they went to.
        tests:
          - not_null
          - relationships:
              to: ref('covid19datos_v2_casos_city_names')
              field: city
              where: >
                city NOT IN ('OTROS', 'NO_DOMICILIADO')
                    AND region NOT IN ('FUERA_DE_PR')
      - name: region
        description: >
          What region is recorded for the case.  Some official documentation
          suggests this is supposed to mean where the patient resides, but there
          has often been reason to suspect many cases might be recorded as the
          region of the test center they went to.
        tests:
          - not_null:
              where: >
                city NOT IN ('ST_THOMAS')
          - relationships:
              to: ref('covid19datos_v2_casos_region_names')
              field: region
  - name: defunciones
    description: >
      The Puerto Rico Department of Health's daily COVID-19 deaths datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per death.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null:
              where: >
                downloaded_date < DATE '2023-05-12'
      - name: co_region
        description: >
          What region is recorded for the death.
        tests:
          - relationships:
              to: ref('covid19datos_v2_casos_region_names')
              field: region
      - name: co_clasificacion
        description: >
          What type of death this record represents, "confirmed" or "probable."
        tests:
          - not_null:
              where: >
                downloaded_date < DATE '2023-05-12'
          - accepted_values:
              values:
                - CONFIRMADO
                - CONFIRMED
                - PROBABLE
      - name: fe_muerte
        description: Date of death.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: DATE '2020-03-01'
              max_value: downloaded_at
              inclusive: true
              error_if: ">3"
  - name: pruebas
    description: >
      The Puerto Rico Department of Health's daily COVID-19 tests datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per test.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: fe_prueba
        description: >
          The date the test sample was collected.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: DATE '2020-03-01'
              max_value: downloaded_at
              inclusive: true
              severity: warn
      - name: co_tipo
        description: >
          What type of test this is (antigen vs. NAAT).
        tests:
          - not_null:
              where: >
                downloaded_date < DATE '2023-05-12'
          - accepted_values:
              values:
                - ANTIGENO
                - MOLECULAR
                - SEROLOGICA
      - name: co_resultado
        description: >
          The test's result.
        tests:
          - not_null:
              severity: warn
          - accepted_values:
              values:
                - NEGATIVA
                - NO_CONCLUYENTE
                - POSITIVA
      - name: co_region
        description: >
          What region is recorded for the test.  Some official documentation
          suggests this is supposed to mean where the patient resides, but there
          has often been reason to suspect many cases might be recorded as the
          region of the test center they went to.
        tests:
          - relationships:
              to: ref('covid19datos_v2_casos_region_names')
              field: region
  - name: sistemas_salud
    description: >
      The Puerto Rico Department of Health's daily COVID-19 hospitals datasets.
      We make one (or more) download per day and keep them all, as tracked
      by the `downloaded_at` column.  The dataset is one record per reported date.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: fe_reporte
        description: >
          The date this record reports about.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: DATE '2020-03-01'
              max_value: downloaded_at
              inclusive: true
  - name: vacunacion
    description: >
      The Puerto Rico Department of Health's daily COVID-19 vaccination datasets.
      We make one (or more) download per day and keep them all, as tracked by the
      `downloaded_at` column.  The dataset is one record per administered dose.
    columns:
      - name: downloaded_at
        description: '{{ doc("downloaded_at") }}'
        tests:
          - not_null
      - name: fe_vacuna
        description: Date that the dose was administered.
        tests:
          - not_null
          - dbt_utils.accepted_range:
              min_value: DATE '2020-12-01'
              max_value: downloaded_at
              inclusive: true
              severity: warn
      - name: co_manufacturero
        description: >
          A code for the manufacturer of the vaccine that was administered.
        tests:
          - accepted_values:
              values:
                - JSN
                - MOD
                - PFR
      - name: nu_dosis
        description: >
          The "number" of the dose for the patient who received this dose.  It's
          not the least bit clear (and likely not at all consistent anyway) whether
          this really is how many doses the patient has received or whether, for
          example, a patient who first gets a one-dose vaccine and then a booster
          would be doses "1" and "3".
        tests:
          - dbt_utils.accepted_range:
              min_value: 0
              max_value: 3
              inclusive: true
              enabled: false
      - name: co_municipio
        description: >
          What municipality is recorded for the dose.  It's not clear if this is
          meant to be where the patient resides or where the dose was administered,
          but it's likely a mix.
        tests:
          - not_null:
              # The first data set published for this was really dirty
              enabled: false  # Scans 1.76 GB and growing
              where: >
                downloaded_date != DATE '2021-07-24'
          - relationships:
              enabled: false
              to: ref('covid19datos_v2_vacunacion_city_names')
              field: city
              where: >
                downloaded_date != DATE '2021-07-24'
