name: 'covid_19_puerto_rico_etl'
version: '1.0.0'
config-version: 2

profile: 'covid-19-puerto-rico-athena'

vars:
  # These dates recur all over:
  first_sample_date: '2020-03-09'
  first_bulletin_date: '2020-04-24'
  first_vax_date: '2020-12-03'
  end_date: '2023-12-31'
  beginning_of_time: '0001-01-01'
  end_of_time: '9999-12-31'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
# TODO: reenable
#analysis-paths: ["analysis"]
analysis-paths: []
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_modules"

# Athena hates the query comments often, so we disable them
query-comment: null


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  covid_19_puerto_rico_etl:
    +table_type: 'iceberg'
    biostatistics:
      cases:
        +materialized: table
      deaths:
        +materialized: table
      encounters:
        +materialized: table
      specimens:
        +materialized: table
      staging:
        +materialized: table
    covid19datos_v2:
      staging:
        +materialized: table
      summaries:
        +materialized: table
    hhs:
      staging:
        +materialized: table
      summaries:
        +materialized: table
    Walgreens:
      staging:
        materialized: table
    reports:
      +materialized: view
    summaries:
      +materialized: table

seeds:
  covid_19_puerto_rico_etl:
    census:
      acs_2019_5y_family_income:
        +column_types:
          fips: VARCHAR(5)
      acs_2019_5y_household_income:
        +column_types:
          fips: VARCHAR(5)
      acs_2019_5y_race:
        +column_types:
          fips: VARCHAR(5)
      municipal_population:
        +column_types:
          fips: VARCHAR(5)

    covid19datos_v2:
      covid19datos_v2_casos_city_names:
        +column_types:
          fips: VARCHAR(5)
      covid19datos_v2_vacunacion_city_names:
        +column_types:
          fips: VARCHAR(5)

    testing:
      expected_test_results:
        +column_types:
          # I'd like BOOLEAN here, but DBT won't load it
          positive: VARCHAR(5)

    other:
      municipal_abbreviations:
        +column_types:
          county: VARCHAR(3)
          fips: VARCHAR(5)
