covid-19-puerto-rico-athena:
  target: prod
  outputs:
    prod:
      type: athena
      region_name: "{{ env_var('AWS_REGION') }}"
      s3_staging_dir: "{{ env_var('ATHENA_S3_STAGING_DIR') }}"
      schema: "{{ env_var('ATHENA_S3_SCHEMA') }}"
      database: "{{ env_var('ATHENA_DATABASE', 'awsdatacatalog') }}"
      work_group: "{{ env_var('ATHENA_WORK_GROUP') }}"
      threads: "{{ env_var('ATHENA_THREADS', 20) | as_number }}"

config:
  use_colors: False