name: csv2parquet Docker image

on:
  workflow_dispatch:

  push:
    branches:
      - 'master'
    paths:
      - '.github/workflows/BUILD_CSV2PARQUET_IMAGE.yml'
      - 'csv2parquet/**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Don't put the usual "Set up QEMU" action here,
      # because we want to cross-compile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: csv2parquet
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            sacundim/csv2parquet:latest
